version: "3"
services:
  webserver:
    build:
      context: ./.docker/nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "6080:80"
      - "60443:443"
    working_dir: /var/www
    volumes:
      - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/nginx/logs:/var/log/nginx/
      - ./app:/var/www/
    depends_on:
      - php
    command: [nginx-debug, '-g', 'daemon off;']

  php:
    build:
      context: ./.docker/php
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./app:/var/www/
    ports:
      - '9000:9000'
    expose:
      - '9000'
